# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: casaos-job-management
before:
  hooks:
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - go test -race -v ./... -timeout 30m
builds:
  - id: casaos-job-management-amd64
    binary: build/sysroot/usr/bin/casaos-job-management
    env:
      - CC=x86_64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-job-management-arm64
    binary: build/sysroot/usr/bin/casaos-job-management
    env:
      - CC=aarch64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-job-management-arm-7
    binary: build/sysroot/usr/bin/casaos-job-management
    env:
      - CC=arm-linux-gnueabihf-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
archives:
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
    id: casaos-job-management
    builds:
      - casaos-job-management-amd64
      - casaos-job-management-arm64
      - casaos-job-management-arm-7
    files:
      - build/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: IceWhaleTech
    name: CasaOS-JobManagement
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
