openapi: 3.0.3

info:
  title: Job Management API
  version: v2

servers:
  - url: /v2/job_management

tags:
  - name: Job methods
    description: Methods for managing jobs

  - name: Job
    description: <SchemaDefinition schemaRef="#/components/schemas/job"/>

x-tagGroups:
  - name: Methods
    tags:
      - Job methods

  - name: Schemas
    tags:
      - Job

security:
  - access_token: []

paths:
  /jobs:
    get:
      summary: Get all jobs
      operationId: job_list
      tags:
        - Job methods
      responses:
        "200":
          $ref: "#/components/responses/job_list_ok"
        "500":
          $ref: "#/components/responses/response_internal_server_error"

    post:
      summary: Create a job
      operationId: create_job
      tags:
        - Job methods
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/job"
      responses:
        "200":
          $ref: "#/components/responses/job_ok"
        "400":
          $ref: "#/components/responses/response_bad_request"
        "500":
          $ref: "#/components/responses/response_internal_server_error"

  /jobs/{id}:
    get:
      summary: Get job by ID
      operationId: job_by_id
      tags:
        - Job methods
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":  
          $ref: "#/components/responses/job_ok"
        "404":
          $ref: "#/components/responses/response_not_found"
        "500":
          $ref: "#/components/responses/response_internal_server_error"

components:
  securitySchemes:
    access_token:
      type: apiKey
      in: header
      name: Authorization

  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/job_id"
      x-go-name: ID

  responses:
    response_ok:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "OK"
      x-go-name: ResponseOK

    response_conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Conflict"

    response_internal_server_error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Internal Server Error"

    response_not_found:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Not Found"

    response_bad_request:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Bad Request"

    job_ok:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/base_response"
              - properties:
                  data:
                    $ref: "#/components/schemas/job"

    job_list_ok:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/base_response"
              - properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/job"
      x-go-name: JobListOK

  schemas:
    base_response: # Every response should inherit from BaseResponse
      properties:
        message:
          description: message returned by server side if there is any
          type: string

    job_id:
      readOnly: true
      type: integer
      format: int64
      x-go-name: JobID

    job:
      required:
        - source_id
      properties:
        id:
          allOf:
            - $ref: "#/components/schemas/job_id"
          x-go-name: ID
          
        source_id:
          type: string
          description: job source ID to identify where the job comes from
          example: "local-storage"
